### ISSUE TITLE
namespace error with sidekiq 2.17.1

### ISSUE THREAD

**Issue by hd-deman** [harvesthq/sidekiq-monitor-stats#1]
```
ameError - uninitialized constant Sidekiq::ProcessSet:
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/sidekiq-monitor-stats-0.0.1/lib/sidekiq/monitor/stats.rb:18:in `process_metrics'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/sidekiq-monitor-stats-0.0.1/lib/sidekiq/monitor/web.rb:13:in `block in registered'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1541:in `call'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1541:in `block in compile!'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:950:in `[]'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:950:in `block (3 levels) in route!'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:966:in `route_eval'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:950:in `block (2 levels) in route!'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:987:in `block in process_route'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:985:in `catch'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:985:in `process_route'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:948:in `block in route!'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:947:in `each'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:947:in `route!'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1059:in `block in dispatch!'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1041:in `block in invoke'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1041:in `catch'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1041:in `invoke'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1056:in `dispatch!'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:882:in `block in call!'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1041:in `block in invoke'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1041:in `catch'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1041:in `invoke'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:882:in `call!'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:870:in `call'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/rack-1.4.7/lib/rack/auth/basic.rb:25:in `call'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/rack-protection-1.5.0/lib/rack/protection/xss_header.rb:18:in `call'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/rack-protection-1.5.0/lib/rack/protection/path_traversal.rb:16:in `call'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/rack-protection-1.5.0/lib/rack/protection/json_csrf.rb:18:in `call'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/rack-protection-1.5.0/lib/rack/protection/base.rb:49:in `call'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/rack-protection-1.5.0/lib/rack/protection/base.rb:49:in `call'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/rack-protection-1.5.0/lib/rack/protection/frame_options.rb:31:in `call'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/rack-1.4.7/lib/rack/nulllogger.rb:9:in `call'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/rack-1.4.7/lib/rack/head.rb:9:in `call'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:175:in `call'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1949:in `call'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1449:in `block in call'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1726:in `synchronize'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1449:in `call'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/journey-1.0.4/lib/journey/router.rb:68:in `block in call'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/journey-1.0.4/lib/journey/router.rb:56:in `each'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.18/lib/action_dispatch/routing/route_set.rb:608:in `call'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/apipie-rails-0.0.24/lib/apipie/static_dispatcher.rb:65:in `call'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/omniauth-1.1.4/lib/omniauth/strategy.rb:184:in `call!'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/omniauth-1.1.4/lib/omniauth/strategy.rb:164:in `call'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/omniauth-1.1.4/lib/omniauth/strategy.rb:184:in `call!'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/omniauth-1.1.4/lib/omniauth/strategy.rb:164:in `call'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/omniauth-1.1.4/lib/omniauth/strategy.rb:184:in `call!'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/omniauth-1.1.4/lib/omniauth/strategy.rb:164:in `call'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/request_store-1.0.5/lib/request_store/middleware.rb:9:in `call'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/warden-1.2.3/lib/warden/manager.rb:35:in `block in call'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `catch'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `call'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.18/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/rack-1.4.7/lib/rack/etag.rb:23:in `call'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/rack-1.4.7/lib/rack/conditionalget.rb:25:in `call'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.18/lib/action_dispatch/middleware/head.rb:14:in `call'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.18/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.18/lib/action_dispatch/middleware/flash.rb:242:in `call'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/rack-1.4.7/lib/rack/session/abstract/id.rb:210:in `context'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/rack-1.4.7/lib/rack/session/abstract/id.rb:205:in `call'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.18/lib/action_dispatch/middleware/cookies.rb:341:in `call'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/activerecord-3.2.18/lib/active_record/query_cache.rb:64:in `call'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/activerecord-3.2.18/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.18/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/activesupport-3.2.18/lib/active_support/callbacks.rb:405:in `_run__3667456617223080528__call__3947710605608033343__callbacks'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/activesupport-3.2.18/lib/active_support/callbacks.rb:405:in `__run_callback'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/activesupport-3.2.18/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/activesupport-3.2.18/lib/active_support/callbacks.rb:81:in `run_callbacks'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.18/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/rack-1.4.7/lib/rack/sendfile.rb:102:in `call'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.18/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.18/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.18/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/lograge-0.3.4/lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/railties-3.2.18/lib/rails/rack/logger.rb:16:in `block in call'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/activesupport-3.2.18/lib/active_support/tagged_logging.rb:22:in `tagged'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/railties-3.2.18/lib/rails/rack/logger.rb:16:in `call'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/ahoy_matey-1.0.1/lib/ahoy/engine.rb:20:in `call_with_quiet_ahoy'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.18/lib/action_dispatch/middleware/request_id.rb:22:in `call'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/rack-1.4.7/lib/rack/methodoverride.rb:21:in `call'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/rack-1.4.7/lib/rack/runtime.rb:17:in `call'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/activesupport-3.2.18/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/rack-utf8_sanitizer-1.1.0/lib/rack/utf8_sanitizer.rb:12:in `call'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/rack-1.4.7/lib/rack/auth/basic.rb:25:in `call'
    /home/deploy/projects/excursiopedia/releases/20150716153543/config/environments/staging_docker.rb:11:in `call'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/rack-1.4.7/lib/rack/lock.rb:15:in `call'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/rack-rewrite-1.5.0/lib/rack/rewrite.rb:24:in `call'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:136:in `forward'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:245:in `fetch'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:185:in `lookup'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:66:in `call!'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:51:in `call'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/honeybadger-1.11.0/lib/honeybadger/rack.rb:42:in `call'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/honeybadger-1.11.0/lib/honeybadger/user_feedback.rb:23:in `call'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/honeybadger-1.11.0/lib/honeybadger/user_informer.rb:12:in `call'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/railties-3.2.18/lib/rails/engine.rb:484:in `call'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/railties-3.2.18/lib/rails/application.rb:231:in `call'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/railties-3.2.18/lib/rails/railtie/configurable.rb:30:in `method_missing'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/puma-2.7.1/lib/puma/configuration.rb:68:in `call'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/puma-2.7.1/lib/puma/server.rb:486:in `handle_request'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/puma-2.7.1/lib/puma/server.rb:357:in `process_client'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/puma-2.7.1/lib/puma/server.rb:250:in `block in run'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/puma-2.7.1/lib/puma/thread_pool.rb:92:in `call'
    /home/deploy/projects/excursiopedia/shared/bundle/ruby/2.0.0/gems/puma-2.7.1/lib/puma/thread_pool.rb:92:in `block in spawn_thread'
```

**Comment by hd-deman** [comment]
change old config value Shellcheck Executable Messages from `/usr/local/bin/shellcheck` to `/usr/local/bin/shellcheck` fix it.
